✨ source:
- src/**/*.py

🚓 test:
- tests/**/*.py

🔧 config:
- "**/*.yaml"
- "**/*.yml"
- "**/*.toml"
- "**/*.lock"
- "**/*.ini"
- "**/*.json"
- .gitignore

🐳 docker:
- Dockerfile
- docker-compose.yml
- .dockerignore

🔨 make:
- Makefile

👷 ci:
- .github/*.yml
- .github/workflows/**/*

📚 docs:
- "**/*.md"
