name: "Pull Request Labeler"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
